# fly.toml app configuration file generated for resume-ai-xod7vw on 2025-10-22T14:08:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'resume-ai-xod7vw'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024