app = "resume-ai"

[env]
PORT = "8080"

[experimental]
allowed_public_ports = [8080]
auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]